config/routes.rb
FeatureGate::Engine.routes.draw do
  resources :gated_features, only: [:index, :update, :destroy]
  get '/' => 'gated_features#index'
end

app/models/feature_gate/gated_feature.rb
module FeatureGate
  class GatedFeature < ActiveRecord::Base
    self.table_name = 'feature_gate_gated_features'

    validates :name, presence: true
    validates :gated, inclusion: { in: [true, false] }

    scope :opened, -> { where(gated: false) }
    scope :closed, -> { where(gated: true) }
    scope :stale, -> { where('updated_at != created_at and updated_at < ?', Time.zone.now - FeatureGate.configuration.time_to_stale) }

    def deploy_feature!
      self.gated = false
      save!
    end

    def gate_feature!
      self.gated = true
      save!
    end

    def status
      if gated
        'closed'
      else
        'opened'
      end
    end

    def destroyable?
      regex = /FeatureGate::Manager.gate(\(|\s)('|")#{name}('|")|FeatureGate::Manager.gate_page(\(|\s)('|")#{name}('|")/
      files = Dir["#{Dir.pwd}/app/views/**/*.html.erb"] + Dir["#{Dir.pwd}/app/controllers/**/*.rb"]

      files.each do |file|
        f = File.new(file)
        text = f.read
        return false if text =~ regex
      end

      true
    end
  end
end

app/models/feature_gate/manager.rb
module FeatureGate
  class Manager
    def self.gate_page(name)
      gated_feature = GatedFeature.where(name: name).first_or_create
      if gated_feature.gated?
        raise ActionController::RoutingError.new('Not Found')
      end
    end

    def self.gate(name)
      gated_feature = GatedFeature.where(name: name).first_or_create
      if !gated_feature.gated?
        yield
      end
    end

    def self.opened_gates
      GatedFeature.opened.pluck(:name)
    end

    def self.closed_gates
      GatedFeature.closed.pluck(:name)
    end

    def self.stale_gates
      GatedFeature.stale.pluck(:name)
    end

    def self.open!(name)
      gated_feature = GatedFeature.find_by_name!(name)
      gated_feature.deploy_feature!
    end

    def self.close!(name)
      gated_feature = GatedFeature.find_by_name!(name)
      gated_feature.gate_feature!
    end

    def self.destroy!(name)
      gate = GatedFeature.find_by_name!(name)
      if gate.destroyable?
        gate.destroy!
        puts "#{gate.name} destroyed"
      else
        puts "#{gate.name} is currently being used in the codebase, execute `feature_gate_cleaner #{gate.name}` in the terminal to remove all references to #{gate.name}"
      end
    end
  end
end

app/controllers/feature_gate/gated_features_controller.rb
module FeatureGate
  class GatedFeaturesController < ApplicationController
    before_filter :ensure_feature_gate_control_allowed
    layout 'feature_gate/application'

    def index
      @closed_gates = FeatureGate::GatedFeature.closed
      @opened_gates = FeatureGate::GatedFeature.opened
      @stale_gates = FeatureGate::GatedFeature.stale.order(:updated_at)
    end

    def update
      gate = FeatureGate::GatedFeature.find(params[:id])
      if params[:gated] == 'true'
        gate.gate_feature!
        flash[:notice] = "#{gate.name} has been gated"
      else
        gate.deploy_feature!
        flash[:success] = "#{gate.name} is live!"
      end

      redirect_to gated_features_path
    end

    def destroy
      gate = FeatureGate::GatedFeature.find(params[:id])
      if gate.destroyable?
        gate.destroy!
        flash[:success] = "#{gate.name} has been deleted"
      else
        flash[:error] = "#{gate.name} is currently being used in the codebase, execute `feature_gate_cleaner #{gate.name}` in the terminal to remove all references to #{gate.name}"
      end

      redirect_to gated_features_path
    end

    private

    define_method(:feature_gate_control_allowed?) do
      true
    end unless method_defined? :feature_gate_control_allowed?

    def ensure_feature_gate_control_allowed
      return if feature_gate_control_allowed?
      raise ActionController::RoutingError.new('Not Found')
    end
  end
end

app/views/feature_gate/gated_features/index.html.erb
<h1>Feature Gates</h1>

<section class="gates">
  <h3>Opened Gates</h3>
  <% if @opened_gates.any? %>
    <table>
      <tr>
        <th>Gate name</th>
        <th>Action</th>
      </tr>

      <% @opened_gates.each do |gate| %>
        <tr>
          <td><%= gate.name %></td>
          <td><%= link_to 'Close', gated_feature_path(gate, gated: true), method: :put, data: { confirm: "Shutting down #{gate.name}, are you sure?" } %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <em>No opened gates</em>
  <% end %>
</section>

<section class="gates">
  <h3>Closed Gates</h3>
  <% if @closed_gates.any? %>
    <table>
      <tr>
        <th>Gate name</th>
        <th>Action</th>
      </tr>

      <% @closed_gates.each do |gate| %>
        <tr>
          <td><%= gate.name %></td>
          <td><%= link_to 'Open', gated_feature_path(gate, gated: false), method: :put, data: { confirm: "Deploying #{gate.name}, are you sure?" } %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <em>No closed gates</em>
  <% end %>
</section>

<hr>

<section class="gates">
  <h3>Stale Gates</h3>
  <% if @stale_gates.any? %>
    <table>
      <tr>
        <th>Gate name</th>
        <th>Status</th>
        <th>Last updated at</th>
        <th>Action</th>
      </tr>

      <% @stale_gates.each do |gate| %>
        <tr>
          <td><%= gate.name %></td>
          <td><%= gate.status %></td>
          <td><%= gate.updated_at.strftime('%F') %></td>
          <td><%= link_to 'Destroy', gated_feature_path(gate), method: :delete, data: { confirm: "Destroying #{gate.name}, are you sure?" } %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <em>No stale gates</em>
  <% end %>
</section>

app/views/layouts/feature_gate/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <title>FeatureGate</title>
  <%= stylesheet_link_tag 'feature_gate/application.scss' %>
  <%= javascript_include_tag 'feature_gate/application.js', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <div class="content alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <div class="content">
    <%= yield %>
  </div>
</body>
</html>